services:
    backend-laravel:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        restart: always
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - net-backend
        depends_on:
            - db-mysql-laravel
            - db-mysql-shop
    db-mysql-laravel:
        image: 'mysql/mysql-server:8.0'
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_MYSQL_LARAVEL_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_MYSQL_LARAVEL_DATABASE}'
            MYSQL_USER: '${DB_MYSQL_LARAVEL_USERNAME}'
            MYSQL_PASSWORD: '${DB_MYSQL_LARAVEL_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'vol-db-mysql-laravel:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - net-backend
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_MYSQL_LARAVEL_PASSWORD}'
            retries: 3
            timeout: 5s
    db-mysql-shop:
        image: 'mysql/mysql-server:8.0'
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3307}:3307'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_MYSQL_SHOP_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_MYSQL_SHOP_DATABASE}'
            MYSQL_USER: '${DB_MYSQL_SHOP_USERNAME}'
            MYSQL_PASSWORD: '${DB_MYSQL_SHOP_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'vol-db-mysql-shop:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - net-backend
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_MYSQL_SHOP_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - db-mysql-laravel
            - db-mysql-shop
        image: phpmyadmin:5.2.2-apache
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ../volumes/tutorial-phpMyadmin/sessions:/sessions:rw
        environment:
            PMA_HOST: db
            PMA_ARBITRARY: 1
        networks:
            - net-backend
networks:
    net-backend:
        driver: bridge
volumes:
    vol-db-mysql-laravel:
        driver: local
    vol-db-mysql-shop:
        driver: local